name: CI

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install git-secret
        run: |
          sudo sh -c "echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list"
          wget -qO - https://gitsecret.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install git-secret
          git secret --version

      - name: Decode secret assets
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --no-tty --import
          git secret reveal -p "$GPG_SECRET_PASSPHRASE"
        env:
          GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
          GPG_SECRET_PASSPHRASE: ${{secrets.GPG_SECRET_PASSPHRASE}}

